version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - unused
    - wrapcheck
  settings:
    gosec:
      excludes:
        - G120
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: error-strings
    wrapcheck:
      ignore-package-globs:
        - github.com/heartleo/subtrans/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/heartleo/subtrans
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
